#!/usr/bin/env python3
import subprocess
import sys
import json

cmd = 'nc -U /run/libvirt/libvirt-sock'

username = sys.argv[1]
try :
    keys = subprocess.check_output(["/usr/bin/sss_ssh_authorizedkeys", username]).decode().splitlines()
except subprocess.CalledProcessError as e:
    pass
    exit(e.returncode)

if len(keys) == 0 :
    exit()

with open("/var/cache/selfnet-sudoers.json", "r") as fi:
    sudoers = json.load(fi)

can_sudo = username in sudoers
prefix = ""
if not can_sudo : #restrict non-sudoers to libvirt socket
    prefix = f'command="{cmd}",restrict '

for key in keys :
    print(prefix + key)
